### ISSUE TITLE
Could you explain what exactly is the `rel_coef` argument? 

### ISSUE THREAD

**Issue by kevalshah90** [nickkunz/smogn#24]
What aspect of box plot variation does it measure?

**Comment by israt183** [comment]
It decides the extents of the whiskers of the box plot. See the code [box_plot_stats.py](https://github.com/nickkunz/smogn/blob/master/smogn/box_plot_stats.py)

**Comment by nickkunz** [comment]
@kevalshah90 thank you for your question. Please refer to the suggestion made by @israt183. If you still have questions, please let us know.
