### ISSUE TITLE
nominal / categorical features

### ISSUE THREAD

**Issue by shaddyab** [nickkunz/smogn#3]
How are independent nominal / categorical features are identified and differentiated from numerical features? Is there is a way to pre-specify them?

**Comment by neverfox** [comment]
I'm not certain but I imagine as long as they're not a numeric type but are instead object or category, they would be treated as such?

**Comment by nickkunz** [comment]
Hello @shaddyab. Thank you for your question. @neverfox is correct. Nominal / categorical features are identified by the data type specified in the pandas dataframe passed into `smoter`'s `data` argument. If the data type of the respective feature is not either an int or float type, it is treated as nominal / categorical.

**Comment by shaddyab** [comment]
@nickkunz In this case one-hot encoding is not needed prior to running SMOTER.

**Comment by nickkunz** [comment]
@shaddyab Please let me know if that answered your question. If so, I will close the issue.

**Comment by shaddyab** [comment]
@nickkunz Thank you for taking the time to answer my question.
