### ISSUE TITLE
The possibility of applying this method in the field of images

### ISSUE THREAD

**Issue by v3551G** [nickkunz/smogn#42]
This is an interesting work. I'm wandering if it can be used in the field of computer vision, where the input has a two-dimensional structure.

**Comment by nickkunz** [comment]
Hello, 

Thank you for your question. I would not advise applying this particular technique in that way. However, I do believe that there are papers related to computer vision, specifically "Delving into Deep Imbalanced Regression."

Unfortunately, I've attempted to reach out to the first author of the paper in reference regarding some of the implementation details that have largely been ignored with some reasonable suspicion of plagiarism and re-licensing this software.

Ref: https://arxiv.org/abs/2102.09554
