### ISSUE TITLE
Documentation on the relevance value matrix 

### ISSUE THREAD

**Issue by MouadEt-tali** [nickkunz/smogn#47]
I've been reading everywhere in the docs and code to understand the meaning of these arrays yet I still can't find the correct answer : 

- do these arrays mean that we'll oversample the value 35000 itself and undersample the other 3 values ?

-  or we'll over sample a certain range around this value for example the range [35000 - X : 35000 + X ]

- Or we'll oversample the range 35000 to 125000 and undersample the range 125000 to 250000 ... 

## Here are the arrays I'm talking about
```
## specify phi relevance values
rg_mtrx = [

    [35000,  1, 0],  ## over-sample ("minority")
    [125000, 0, 0],  ## under-sample ("majority")
    [200000, 0, 0],  ## under-sample
    [250000, 0, 0],  ## under-sample
]
```

**Comment by nickkunz** [comment]
You’ve understood the relevance matrix correctly in your first statement. You are oversampling the value 35,000 and undersampling the other three.

**Comment by MouadEt-tali** [comment]
That does help  but it leaves my team and I a bit confused. 

Our target variable ranges from 1 to 450 with high density around the 1 - 25 area and low/rare values after the 120 mark. Does this mean we have to specify in the matrix all the values 120 to 450 ( which means 320 arrays of the form [X,1,0] ) ?

That sounds even more impossible in other regression problems (example house prices).

**Comment by nickkunz** [comment]
No. This does not mean you have to specify the matrix with all continuous values between 120 and 450. I'd encourage your team to revisit the original paper if this is confusing. The phi() relevance function is what you are looking for. You might think of the oversampled observations corresponding to the relevance matrix as being "about" the specified values in that regard.
