### ISSUE TITLE
Random Seed Implementation

### ISSUE THREAD

**Issue by ArnoldYSYeung** [nickkunz/smogn#9]
Would it be possible to have an argument for random seed so that we can reproduce results?

**Comment by nickkunz** [comment]
Yes! That is a great idea. I've been meaning to do exactly that. I will take note of this in the next implementation. Thank you.

**Comment by Muti23** [comment]
I have the same request. IS there any progress in this part?
Thanks for your sharing.

**Comment by ArnoldYSYeung** [comment]
@Muti23 Bro I'll do it. It shouldn't be difficult. Ping me in 1 month's time if I haven't submitted any pull request. Gotta do my taxes first.

**Comment by ArnoldYSYeung** [comment]
@nickkunz Please review. Thanks bro 
https://github.com/nickkunz/smogn/pull/27

**Comment by nickkunz** [comment]
The following issue has been resolved by the following PR: https://github.com/nickkunz/smogn/pull/28. This contribution was made by @ArnoldYSYeung. Thank you for your help!
